### ISSUE TITLE
Display List of news events

### ISSUE THREAD

**Issue by JakobRaap** [JakobRaap/capstone-project-economic-calendar#1]
## Value proposition

As a user
I want to see a list of todays economic news events
in order to be prepared for the upcoming trading day

## Description

![Untitled-2023-04-02-1433(4)](https://user-images.githubusercontent.com/127104766/236150672-7e8eac71-5b9f-4938-8c73-eb47b38848c6.png)

## Acceptance criteria

- [ ] each event has an own card
- [ ] the card displays the name of the event, the time, the impact level and the country
-

## Tasks

- [ ] create a new branch
- [ ] fetch todays data from the API
- [ ] render the events into an unordered list
- [ ] apply a minimal styling to each list item so that it is displayed as a card

**Comment by mbosselmann** [comment]
Hi Jakob,
great first user story! 👍 I have some remarks for you to consider:

## Description

- your wireframe shows a navigation that is not necessary yet. Therefore, I would remove it from the wireframe as you do not implement a navigation with this user story. Add it to your wireframe when you need a navigation
- same for the part above of your list: if the for now empty spaces are not necessary, then you should remove them. I can understand that a title might be useful to understand the events list. This could be something that you can add until it is not necessary anymore

## Acceptance criteria
- the impact level of each event is not displayed in your wireframe or? This should be changed. 
- And do the flags for each country refer to the currency? 🤔 I am not sure if this solution could be misleading and you should name the currency instead. If the country flag refers to something else, it would be useful if you describe it in your acceptance criteria

And if you do not want to set a size for your user story (this is optional) then you can remove this part. With size you can decide what you think is the complexity of your user story (usually small, medium or large).

I hope this does help! Feel free to ask if you have questions. :)

**Comment by mbosselmann** [comment]
Hi Jakob,
great work!  💪 Your user story is approved. ✅
