### ISSUE TITLE
Alarms Page

### ISSUE THREAD

**Issue by JakobRaap** [JakobRaap/capstone-project-economic-calendar#10]
## Value proposition

As a User
I want to be able to toggle an alarm for each event
in order to get warned before the event happens

## Description

![Untitled-2023-04-02-1433(13)](https://github.com/JakobRaap/capstone-project-economic-calendar/assets/127104766/72edd93d-4ac7-4903-8e28-8c95d48210e5)
![Untitled-2023-04-02-1433(14)](https://github.com/JakobRaap/capstone-project-economic-calendar/assets/127104766/c0eff91f-842b-4b27-bd42-d2c72b3ac8e2)

## Acceptance criteria

- [ ] Each event card has to have an alarm button, that can be toggled
- [ ] The Alarms-page should display all active alarms
- [ ] The toggled alarms should still be shown after refreshing the page
- [ ] Possibility to navigate between the pages
- [ ] Navigation between daily and weekly events

## Tasks

- [ ] Create a alarms.js page that renders all events with alarm===true
- [ ] Import Alarm-icons
- [ ] Add the alarm-toggle button to all the cards
- [ ] Create a handleAlarmToggle function 
- [ ] Save the alarm state in the local storage of the browser
- [ ] Add a navigation bar at the bottom to navigate between the different pages
- [ ] Add a navigation bar at the top of the calendar page with a link for the daily and the weekly events pages

**Comment by doctype-Melvin** [comment]
lgmt
Let's go!
