### ISSUE TITLE
Calendar event download

### ISSUE THREAD

**Issue by JakobRaap** [JakobRaap/capstone-project-economic-calendar#13]
## Value proposition

As a user
I want to download one or multiple events
in order to transfer them into my calendar

## Description

![Untitled-2023-05-22-1626](https://github.com/JakobRaap/capstone-project-economic-calendar/assets/127104766/88720aa5-e96c-4d18-9b9d-48f39f7fdc49)

## Acceptance criteria

- [ ] The user should be able to download a single event from the event details page as ics file
- [ ] The user should be able to download multiple events from the toggled events page as ics file

## Tasks

- [ ] install the ics Calendar generator package from via npm
- [ ] create a ics-generator.js file in the api folder
- [ ] implement the handling of a single event download and a multiple-event download
- [ ] implement the links to the ics-generator.js for downloading the files
