### ISSUE TITLE
In-App Alarm

### ISSUE THREAD

**Issue by JakobRaap** [JakobRaap/capstone-project-economic-calendar#16]
## Value proposition

As a user
I want to be able to set an alarm for each event
in order to be warned by an alarm sound in advance

## Acceptance criteria

- [ ] if an event has the alarm bell toggled, an alarm sound should be played two minutes before the event

## Tasks

- [ ] create an alarm timer component
- [ ] get the current time and compare it to the alarm events times subtracted by two minutes
- [ ] if one or more alarm event times match the current time, play an alarm message
