### ISSUE TITLE
Show this weeks events

### ISSUE THREAD

**Issue by JakobRaap** [JakobRaap/capstone-project-economic-calendar#2]
## Value proposition

As a Trader
I want to see all upcoming economic news events for this week
in order to plan ahead how my trading week will be structured

## Description

![Untitled-2023-04-02-1433(5)](https://user-images.githubusercontent.com/127104766/236151868-6194b785-ae51-4e07-92ba-6f67ce8b4e80.png)

## Acceptance criteria

- [ ] each event of the week should have an own card
- [ ] each day of the week should be separated by a heading that tells the day and the date

## Tasks

- [ ] render a list with a heading for each day followed by the associated events

**Comment by CJAkkuec** [comment]
Looking good, just a little note! 

>  for every day of the week, create an array with the associated events

I am foreseeing a little bit of pain in your future if you go ahead with this type of database design.

I would suggest something like a "single source of truth" instead:

```javascript
const eventsArray = [
{eventId: 232423IDSfsdfsd2,
//What the date looks like depends on the formatting you choose, so this is just an example.
eventDate: 05-11-23,
eventLocation: US,
//... etc},
{eventId: 345523IDSfsdfsd2,
eventDate: 06-11-23,
eventLocation: GER,
//... etc},
]
```
This way you can map over your single eventsArray and render items according to their date. 👍

**Comment by JakobRaap** [comment]
Sounds good, i will try to implement it that way!
