### ISSUE TITLE
Event details page

### ISSUE THREAD

**Issue by JakobRaap** [JakobRaap/capstone-project-economic-calendar#3]
## Value proposition

As a user,
I want to view detailed information about an economic news event,
in order to understand the event's impact on the economy

## Description
When clicking on an economic news event card, a details page should display the following information:
- Event Name
- Country
- Previous Value
- Forecasted Value
- Impact Level

## Acceptance Criteria
- [ ] The details page should display all the required information
- [ ] The details page should be accessible by clicking on an economic news event card

## Tasks
- [ ] Design the layout of the details page
- [ ] Develop the functionality for accessing the details page from an economic news event card
- [ ] Implement the functionality for displaying the required information on the details page

**Comment by CJAkkuec** [comment]
> Develop the functionality for accessing the details page from an economic news event card
 > Implement the functionality for displaying the required information on the details page

I call this move the ["Draw the Owl"](https://i0.wp.com/seths.blog/wp-content/uploads/2014/01/6a00d83451b31569e2019aff29b7cd970c-450wi.jpg?ssl=1) 😆 

You have to be a little more descriptive in your tasks than "develop the app", so something according to these lines:

[ ] Create a details page `[id].js`
[ ] Implement dynamic routing
[ ] Create an eventDetails component
[ ] ...

This isn't meant to punish you with more work, but this is somehow coding without actually writing code, going through the steps required to build your feature. 👍

**Comment by JakobRaap** [comment]
xDD

> I call this move the ["Draw the Owl"](https://i0.wp.com/seths.blog/wp-content/uploads/2014/01/6a00d83451b31569e2019aff29b7cd970c-450wi.jpg?ssl=1) 😆

**Comment by mbosselmann** [comment]
Hi Jakob,
LGTM! 🦊
