### ISSUE TITLE
Settings Page

### ISSUE THREAD

**Issue by JakobRaap** [JakobRaap/capstone-project-economic-calendar#7]
## Value proposition

As a user
I want to be able to apply some settings to the app
in order to customize what and how things are displayed in the app.

## Description
![Untitled-2023-05-22-1626(2)](https://github.com/JakobRaap/capstone-project-economic-calendar/assets/127104766/b65fd074-ddea-42bb-ab34-7e420306e60f)

## Acceptance criteria

- [ ] The preferred currency section gets activated/deactivated by clicking the preferred currencies checkbox
- [ ] When the preferred currency section is  activated, only the preferred currencies are displayed in the app
- [ ] The user can set a timer for the first and second warning in the calendar events as well as the evenduration

## Tasks

- [ ] Create a Settings Page
- [ ] Create a PreferredCurrencies component
- [ ] Create a CardSettings component
- [ ] Create state variables that get updated via click event handler for the different checkboxes
- [ ] Modify the daily and weekly pages so they conditionally render either all events or favorite events
- [ ] Apply conditional rendering for the forecast value depending on the checkboxes state
