### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by JakobRaap** [JakobRaap/capstone-project-economic-calendar#8]
## Value proposition

As a user
I want a navigation bar
in order to navigate between all pages

## Description

![Untitled-2023-04-02-1433(8)](https://github.com/JakobRaap/capstone-project-economic-calendar/assets/127104766/d685a3fd-6d1d-4293-be79-f3b37dc04d84)

## Acceptance criteria

- [ ] Navigation Bar at the bottom of the page
- [ ] Has to navigate between Today, This Week, Alarms and Settings Page

## Tasks

- [ ] Create a NavigationBar Component
- [ ] Create 4 Links that Navigate between the 4 pages
- [ ] Add a little styling
